#theme: jekyll-theme-minima
title: VMagicMirror
author: 獏星(ばくすたー)
description: VMagicMirror is a mirror-like software to reflect yourself as VRM avatar, without any special devices.

sass:
    style: compressed
